- name: Update base git repo
  git:
    repo: "{{ openwisp2fw_source_repo }}"
    dest: "{{ openwisp2fw_source_dir }}"
    version: "{{ openwisp2fw_source_version }}"

- name: Set feeds.conf
  template:
    src: compile/feeds.conf.jinja2
    dest: "{{ openwisp2fw_source_dir }}/feeds.conf"

- name: Prepare default .config
  template:
    src: compile/.config.jinja2
    dest: "{{ openwisp2fw_source_dir }}/.config.default"

- name: Prepare compile.sh
  template:
    src: compile/compile.sh.jinja2
    dest: "{{ openwisp2fw_source_dir }}/compile.sh"
    mode: 0755

- name: ./compile.sh
  command: ./compile.sh
  args:
    chdir: "{{ openwisp2fw_source_dir }}"
